name: 'my first container action'
description: 'A cloud guru training lab'
author: 'splk3'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'splk3 dont care'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  
